apiVersion: v1
kind: Service
metadata:
  labels:
    service: udagram-api-gateway
  name: udagram-api-gateway-svc
spec:
  type: LoadBalancer
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: udagram-api-gateway

